# Inserts a blank line between shell prompts
add_newline = false

# Use custom format
format = """
[$all](bold green)
[└─$character](bold green)"""

# move the rest of the prompt to the right
right_format = """
$battery$time
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 1000

# makes prompt a single line
[line_break]
disabled = true

[character]
success_symbol = "[▶](green)"
error_symbol = "[▶](fg:#FF9900) "

[username]
disabled = true
show_always = true
style_root = "bold bg:#728da8 fg:#DE935F"
style_user = "bg:#728da8 fg:#222A36"
format = "[[](bg:#728da8 fg:#A6A6A6)$user[](bg:#A6A6A6 fg:#728da8)]($style)"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (= 10 sec)
format = "took [$duration]($style)"

[battery]
# disabled = true
format = "[ $symbol$percentage ]($style)"

[[battery.display]]
threshold = 30
style = "bg:#FF4400 fg:#333333"

[directory]
style = "bg:blue fg:black"
read_only = ""
read_only_style = "bg:#FF6E79 fg:#EEEEEE"
truncation_length = 2
truncate_to_repo = true
truncation_symbol = "…"
format = "([ (bg:#FF6E79 fg:#A6A6A6)$read_only(bg:#A6A6A6 fg:#FF6E79) ]($read_only_style))[ (bg:#545B68 fg:#A6A6A6)$path (bg:#A6A6A6 fg:#545B68)]($style)"

[directory.substitutions]
"~/Documents" = ""
"~/Music" = " "
"~/Movies" = " "
"~/Pictures" = " "
"~/projects" = " "
"~" = " "
"/" = "  "

[git_branch]
format = "[ $symbol$branch ]($style) "
symbol = " "
style = "black bg:green"

[git_commit]
commit_hash_length = 8
style = "bold white"

[gcloud]
disabled = true
symbol = "☁️ "
style = "bg:#1A73E8 fg:#EEEEEE"
format = '[$symbol GCLOUD]($style) '

[helm]
# disabled = true
symbol = "ﴱ "
style = "blue"
format = "[ $symbol$version ]($style)"

[kubernetes]
disabled = false
symbol = "☸︎"
style = "bg:#3371E3 fg:#EEEEEE"
format = '[ $symbol $context(\($namespace\)) (bg:#A6A6A6 fg:#3371E3)]($style)'

[time]
disabled = true
style = "bg:#b4bbc8 fg:#111111"
use_12hr = false
time_format = "%H:%M"
utc_time_offset = "local"
time_range = "20:00:00-06:00:00"
format = "[[](bg:#b4bbc8 fg:#A6A6A6) $time[](bg:#A6A6A6 fg:#b4bbc8)]($style)"

[memory_usage]
format = "$symbol[${ram_pct}]($style) "
threshold = 70
style = "bold dimmed white"
disabled = true

[nodejs]
# disabled = true
symbol = " "
style = "bg:#005F00 fg:#EEEEEE"
format = "[ (bg:#005F00 fg:#A6A6A6)$symbol$version (bg:#A6A6A6 fg:#005F00)]($style)"

[python]
disabled = false
symbol = " "
style = "bg:#EBD45B fg:#111111"
pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[ (bg:#EBD45B fg:#A6A6A6)$symbol$pyenv_prefix$version (\[$virtualenv\] )(bg:#A6A6A6 fg:#EBD45B)]($style)'

[golang]
# disabled = true
symbol = " "
style = "bg:#7FD5EA fg:#111111"
format = "[ (bg:#7FD5EA fg:#A6A6A6)$symbol$version (bg:#A6A6A6 fg:#7FD5EA)]($style)"

[terraform]
disabled = false
symbol = "行"
style = "bg:#5836CD fg:#EEEEEE"
format = '[ (bg:#5836CD fg:#A6A6A6)$symbol (bg:#A6A6A6 fg:#5836CD)]($style)'

[package]
# disabled = true
symbol = " "
style = "bg:#545B68 fg:#EEEEEE"
display_private = false
format = "[ (bg:#545B68 fg:#A6A6A6)$symbol$version (bg:#A6A6A6 fg:#545B68)]($style)"

[status]
# disabled = false
symbol = ""
style = "bg:#A6A6A6 fg:#FF6E79"
format = "[$symbol$status]($style)"

# # Order of modules on prompt
# format = """[](bg:#A6A6A6 fg:#57686B)\
#         $time\
#         $memory_usage\
#         $username\
#         $hostname\
#         $directory\
#         $aws\
#         $gcloud\
#         $kubernetes\
#         $docker_context\
#         $git_branch\
#         $git_commit\
#         $git_status\
#         $git_state\
#         $golang\
#         $nodejs\
#         $python\
#         $terraform\
#         $helm\
#         $package\
#         $custom\
#         $line_break\
#         $battery\
#         $status\
#         $character\
#     """

# [battery]
# # disabled = true
# full_symbol = ""
# charging_symbol = " "
# discharging_symbol = " "
# unknown_symbol = ""
# empty_symbol = ""
# format = "[[](bg:#DE935F fg:#A6A6A6)$symbol$percentage[](bg:#A6A6A6 fg:#DE935F)]($style)"
# [[battery.display]]
# threshold = 20
# style = "bold bg:#DE935F fg:#EEEEEE"
# [[battery.display]]
# threshold = 40
# style = "bg:#DE935F fg:#111111"


# [cmd_duration]
# # disabled = true
# style = "bg:#A6A6A6 fg:#111111"
# min_time = 2_000
# show_milliseconds = true
# show_notifications = true
# min_time_to_notify = 45_000
# format = "[ 祥$duration]($style)"

# [directory]
# style = "bg:#545B68 fg:#EEEEEE"
# read_only = ""
# read_only_style = "bg:#FF6E79 fg:#EEEEEE"
# truncation_length = 4
# truncate_to_repo = true
# # truncation_symbol = "…"
# # fish_style_pwd_dir_length = 3
# format = "([[](bg:#FF6E79 fg:#A6A6A6)$read_only[](bg:#A6A6A6 fg:#FF6E79)]($read_only_style))[[](bg:#545B68 fg:#A6A6A6)$path[](bg:#A6A6A6 fg:#545B68)]($style)"

# [directory.substitutions]
# # "~/Documents" = ""
# # "~/Music" = ""
# # "~/Movies" = ""
# # "~/Pictures" = ""
# # "~/Sources" = ""
# # "~" = " "
# # "/" = "  "

# [docker_context]
# # disabled = true
# symbol = " "
# style = "bg:#3A91DC  fg:#EEEEEE"
# only_with_files = true
# format = "[[](bg:#3A91DC fg:#A6A6A6)$symbol$context[](bg:#A6A6A6 fg:#3A91DC)]($style)"

# [env_var]
# disabled = true
# symbol = " "
# style = "bg:#545B68 fg:#EEEEEE"
# variable = "0"
# default = "fish"
# format = "([[](bg:#545B68 fg:#A6A6A6)$symbol$env_value[](bg:#A6A6A6 fg:#545B68)]($style))"

# [git_branch]
# # disabled = true
# symbol = " "
# # symbol = " " # alternate
# style = "bg:#96ab5f fg:#111111"
# # truncation_length = 4
# # truncation_symbol = ""
# format = "[[](bg:#96ab5f fg:#A6A6A6)$symbol$branch[](bg:#A6A6A6 fg:#96ab5f)]($style)"

# [git_commit]
# # disabled = true
# style = "bg:#E58F73 fg:#111111"
# commit_hash_length = 4
# # only_detached = true
# format = "[[](bg:#E58F73 fg:#A6A6A6)#$hash[](bg:#A6A6A6 fg:#E58F73)]($style)"

# [git_state]
# # disabled = true
# style = "bg:#E0B25D fg:111111"
# rebase = "rebasing"
# merge = "merging"
# revert = "reverting"
# cherry_pick = " picking"
# bisect = "bisecting"
# am = "am'ing"
# am_or_rebase = "am/rebase"
# format = '\([[](bg:#E0B25D fg:#A6A6A6)$state($progress_current/$progress_total)[](bg:#A6A6A6 fg:#E0B25D)]($style)\)'

# [git_status]
# # disabled = true
# style = "bg:#E0B25D fg:#000000"
# stashed = " ${count}"
# ahead = "ﲗ ${count}"
# behind = "ﲔ ${count}"
# diverged = "李 ${ahead_count} ${behind_count}"
# conflicted = "${count}"
# deleted = " ${count}"
# renamed = "﫦${count}"
# modified = " 凜${count}"
# staged = "  ${count}"
# untracked = "  ${count}"
# format = "([[](bg:#E0B25D fg:#A6A6A6)$stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind[](bg:#A6A6A6 fg:#E0B25D)]($style))"

# [ruby]
# # disabled = true
# symbol = " "
# # symbol = " " # alternate
# style = "bg:#CC342D fg:#EEEEEE"
# format = "[[](bg:#CC342D fg:#A6A6A6)$symbol$version[](bg:#A6A6A6 fg:#CC342D)]($style)"

# [shlvl]
# # disabled = false
# symbol = ""
# style = "bold bg:#A6A6A6 fg:#d7bd8d"
# threshold = 2
# format = "[$symbol$shlvl]($style)"
