# Inserts a blank line between shell prompts
add_newline = false

# # Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 1000
command_timeout = 2000

# Use custom format
format = """
[$all$kubernetes$cmd_duration](bold color_green)$fill$gcloud$aws$battery
[└─$character](green)"""

palette = 'ashes_dark'

[palettes.ashes_dark]
color_fg0 = '#c7ccd18'
color_bg0 = '#1c2023'
color_blue = '#ae95c7'
color_cyan = '#95aec7'
color_green = '#95c7ae'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#c7ae95'
color_yellow = '#aec795'
color_white = '#c7ccd1'

[fill]
symbol = " "

# makes prompt a single line
[line_break]
disabled = true

[character]
disabled = false
success_symbol = "[▶](fg:color_green)"
error_symbol = "[▶](fg:color_red)"

[username]
disabled = true
show_always = true
style_root = "bold bg:#728da8 fg:#DE935F"
style_user = "bg:#728da8 fg:#222A36"
format = "[(bg:#728da8 fg:#A6A6A6)$user(bg:#A6A6A6 fg:#728da8)]($style)"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (= 10 sec)
format = " took [$duration]($style)"

[battery]
disabled = true
format = "[ $symbol$percentage ]($style)"

[[battery.display]]
threshold = 30
style = "bg:#FF4400 fg:#333333"

[directory]
style = "bg:blue fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~/Documents" = ""
"~/Downloads" = " "
"~/Music" = " "
"~/Movies" = " "
"~/Pictures" = " "
"~/projects" = " "
"~" = " "
"/" = "/"

[git_branch]
symbol = " "
style = "fg:black bg:color_green"
truncation_length = 15
truncation_symbol = "…"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "fg:black bg:color_green"
format = "([$all_status ]($style))"

[aws]
disabled = true
symbol = "  "
format = '[ $symbol($profile )(\($region\) )]($style)'

[gcloud]
disabled = true
symbol = ' '
style = "bg:#1A73E8 fg:#EEEEEE"
format = '[ $symbol($account )(\($project\) )]($style)'

[ruby]
disabled = false
symbol = " "
style = "bg:#CC342D fg:#EEEEEE"
format = "[ $symbol$version ]($style)"

[helm]
disabled = true
symbol = "ﴱ "
style = "blue"
format = "[ $symbol$version ]($style)"

[kubernetes]
disabled = false
symbol = "☸︎"
style = "bg:color_cyan fg:black"
format = '[ $symbol $context(\($namespace\)) ]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[nodejs]
symbol = ""
style = "bg:color_red fg:black"
format = "[ $symbol $version (bg:blue fg:black)]($style)"

[package]
disabled = true

[rust]
symbol = ""
style = "bg:#eb7a34 fg:black"
format = "[ $symbol $version (bg:blue fg:black)]($style)"

[python]
symbol = " "
style = "bg:color_cyan fg:black"
pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[ $symbol$pyenv_prefix$version (\[$virtualenv\]) ]($style)'

[golang]
symbol = " "
style = "bg:color_green fg:black"
format = "[ $symbol$version ]($style)"

[terraform]
disabled = false
symbol = "行"
style = "bg:#5836CD fg:#EEEEEE"
format = '[ (bg:#5836CD fg:#A6A6A6)$symbol (bg:#A6A6A6 fg:#5836CD)]($style)'
