# Inserts a blank line between shell prompts
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 1000
command_timeout	= 2000

# Use custom format
format = """
[$all](bold green)$fill$gcloud$aws$kubernetes$battery$time
[└─$character](bold green)"""

[fill]
symbol = " "

# makes prompt a single line
[line_break]
disabled = true

[character]
success_symbol = "[▶](green)"
error_symbol = "[▶](fg:#FF9900)"

[username]
disabled = true
show_always = true
style_root = "bold bg:#728da8 fg:#DE935F"
style_user = "bg:#728da8 fg:#222A36"
format = "[[](bg:#728da8 fg:#A6A6A6)$user[](bg:#A6A6A6 fg:#728da8)]($style)"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (= 10 sec)
format = " took [$duration]($style)"

# [env_var]
# disabled = true
# symbol = " "
# style = "bg:#545B68 fg:#EEEEEE"
# variable = "0"
# default = "zsh"
# format = "([ $symbol$env_value ]($style))"

[battery]
# disabled = true
format = "[ $symbol$percentage ]($style)"

[[battery.display]]
threshold = 30
style = "bg:#FF4400 fg:#333333"

[directory]
style = "bg:blue fg:black"
read_only = ""
read_only_style = "bg:#FF6E79 fg:#EEEEEE"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…"
format = "([ $read_only ]($read_only_style))[ $path ]($style)"

[directory.substitutions]
"~/Documents" = ""
"~/Music" = " "
"~/Movies" = " "
"~/Pictures" = " "
"~/projects" = " "
"~" = " "
"/" = "/"

[git_branch]
#symbol = " "
symbol = " " # alternate
style = "black bg:green"
truncation_length = 15
truncation_symbol = "…"
format = "[ $symbol$branch ]($style)"

[git_commit]
# disabled = true
style = "bg:#E58F73 fg:#111111"
commit_hash_length = 8
# only_detached = true
format = "[[](bg:#E58F73 fg:#A6A6A6)#$hash[](bg:#A6A6A6 fg:#E58F73)]($style)"

[git_state]
style = "bg:#E0B25D fg:111111"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '\([ $state($progress_current/$progress_total)]($style)\)'

[git_status]
style = "black bg:#E0B25D"
stashed = " ${count}"
ahead = "ﲗ ${count}"
behind = "ﲔ ${count}"
diverged = "李 ${ahead_count} ${behind_count}"
conflicted = "${count}"
deleted = " ${count}"
renamed = "﫦${count}"
modified = " 凜${count}"
staged = "  ${count}"
untracked = "  ${count}"
format = "([ $stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind ]($style))"

[aws]
disabled = true
symbol = "  "
format = '[ $symbol($profile )(\($region\) )]($style)'

[gcloud]
disabled = true
symbol = ' '
style = "bg:#1A73E8 fg:#EEEEEE"
format = '[ $symbol($account )(\($project\) )]($style)'

[ruby]
# disabled = true
symbol = " "
# symbol = " " # alternate
style = "bg:#CC342D fg:#EEEEEE"
format = "[ $symbol$version ]($style)"

[helm]
# disabled = true
symbol = "ﴱ "
style = "blue"
format = "[ $symbol$version ]($style)"

[kubernetes]
disabled = false
symbol = "☸︎"
style = "bg:#3371E3 fg:#EEEEEE"
format = '[ $symbol $context(\($namespace\)) (bg:#A6A6A6 fg:#3371E3)]($style)'

[time]
disabled = false
style = "bg:#b4bbc8 fg:#111111"
use_12hr = false
time_format = "%H:%M"
utc_time_offset = "local"
#time_range = "20:00:00-06:00:00"
format = "[ $time ]($style)"

[memory_usage]
format = "$symbol[${ram_pct}]($style) "
threshold = 70
style = "bold dimmed white"
disabled = true

[nodejs]
# disabled = true
symbol = " "
style = "bg:#005F00 fg:#EEEEEE"
format = "[ (bg:#005F00 fg:#A6A6A6)$symbol$version (bg:#A6A6A6 fg:#005F00)]($style)"

[python]
disabled = false
symbol = " "
style = "bg:#EBD45B fg:#111111"
pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[ (bg:#EBD45B fg:#A6A6A6)$symbol$pyenv_prefix$version (\[$virtualenv\] )(bg:#A6A6A6 fg:#EBD45B)]($style)'

[golang]
symbol = " "
style = "bg:#7FD5EA fg:#111111"
format = "[ (bg:#7FD5EA fg:#A6A6A6)$symbol$version (bg:#A6A6A6 fg:#7FD5EA)]($style)"

[terraform]
disabled = false
symbol = "行"
style = "bg:#5836CD fg:#EEEEEE"
format = '[ (bg:#5836CD fg:#A6A6A6)$symbol (bg:#A6A6A6 fg:#5836CD)]($style)'

[package]
# disabled = true
symbol = " "
style = "bg:#545B68 fg:#EEEEEE"
display_private = false
format = "[ (bg:#545B68 fg:#A6A6A6)$symbol$version (bg:#A6A6A6 fg:#545B68)]($style)"

[status]
# disabled = false
symbol = ""
style = "bg:#A6A6A6 fg:#FF6E79"
format = "[$symbol$status]($style)"
