live_config_reload = true

import = [
  "~/.config/alacritty/themes/themes/rose-pine.toml"
]

shell = "/opt/homebrew/bin/tmux"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

# move cursor one word right
[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

# move cursor one word left
[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

# move cursor to the beginning
[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

# move cursor to the end
[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

# delete line
[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.98
blur = true

[window.dimensions]
columns = 260
lines = 55

[window.padding]
x = 12
y = 12

[scrolling]
history = 100000
multiplier = 3
