live_config_reload = true
theme = "Ashes.dark"

[colors]
author = "Chris Kempson"
name = "Ashes (dark)"

[colors.bright]
black = "#747c84"
blue = "#ae95c7"
cyan = "#95aec7"
green = "#95c7ae"
magenta = "#c795ae"
red = "#c7ae95"
white = "#f3f4f5"
yellow = "#aec795"

[colors.cursor]
cursor = "#c7ccd1"
text = "#1c2023"

[colors.normal]
black = "#1c2023"
blue = "#ae95c7"
cyan = "#95aec7"
green = "#95c7ae"
magenta = "#c795ae"
red = "#c7ae95"
white = "#c7ccd1"
yellow = "#aec795"

[colors.primary]
background = "#1c2023"
foreground = "#c7ccd1"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 15.0

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002%"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\""
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "Down"
mods = "Command|Shift"

[mouse]
hide_when_typing = true

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.98

[window.dimensions]
columns = 168
lines = 51

[window.padding]
x = 12
y = 12

[window.scrolling]
history = 10000
multiplier = 3
