live_config_reload = true
shell = "/usr/bin/tmux"

import = [
  "~/.config/alacritty/themes/themes/ashes_dark.toml"
]

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.98

[window.dimensions]
columns = 260
lines = 55

[window.padding]
x = 12
y = 12

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[font]
size = 15.0

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

# move cursor one word right
[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

# move cursor one word left
[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

# move cursor to the beginning
[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Control"

# move cursor to the end
[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Control"

# delete line
[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Control"
