name: linux ci

on:
  pull_request:
    paths:
    - 'scripts/linux-*'
    - 'Makefile'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run script
      run: make
