name: linux ci

on:
  pull_request:
    paths:
    - 'scripts/linux-*'
    - '.config/**'

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Run script
      run: make
