name: mac CI

on:
  pull_request:
    paths:
    - 'scripts/mac-setup'
    - '.config/**'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run script
      run: make
